# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: UTM-Hanoi
author: Nick Malleson, Kristina Bratkova, Alexis Comber, Phe Hoang Huu, Minh Kieu, Thanh Bui Quang, Hang Nguyen Thi Thuy, Eric Wanjau

logo: ./assets/img/logo/logo.jpeg
email: n.s.malleson@leeds.ac.uk

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: web.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ./references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Urban-Analytics/UTM-Hanoi  # Online location of your book
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  #favicon                   : "./assets/img/logo/favicon-32x32.png"  # A path to a favicon image
  use_repository_button     : true
  use_issues_button         : true
  use_edit_page_button      : true
  navbar_number_sections    : true  # Add a number to each section in your left navbar
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://github.com/Urban-Analytics/UTM-Hanoi"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  navbar_footer_text        :
    '<div>
    This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </div>'  # Will be displayed underneath the left navbar.
